---

- hosts: all

  tasks:
      - name: Initial setup
        command: timedatectl set-timezone Asia/Tokyo
        become: yes
      - file: path=~/.vim/autoload state=directory
      - git_config: name=user.name value=izumimatsuo scope=global
      - git_config: name=user.email value=gurux2daddy@gmail.com scope=global

      - name: Install vim-plug
        get_url: url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim dest=~/.vim/autoload/plug.vim force=yes

      - name: Download dotfiles
        git: repo=https://github.com/izumimatsuo/dotfiles dest=~/dotfiles
        register: result

      - name: Setup dotfiles
        command: ./install.sh chdir=~/dotfiles
        when: result.changed
